[build]
  command = "gatsby build"
  functions = "functions"
  publish = "public"
  plugins = ["netlify-plugin-gatsby"]
  environment = { NODE_VERSION = "18.12.1" }


[dev]
  command = "gatsby develop"
  port = 8000

